### PR TITLE
Update 2_2.md -> 'Destructuring' part

### PR DESCRIPTION
**Pull request by k0pernicus**
Add a precision about the matching of 'Point' struct in the 'Destructuring' part.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You didn't have to close the previous one. Well, it doesn't matter. Thanks a lot !

**Comment by k0pernicus** [comment]
I have some troubles with the Github website to make & modify some pull requests - that is why I have decided to close the previous PR ;-)
This is what you get for using the Github browser instead of git soft'... Sorry!

**Comment by GuillaumeGomez** [comment]
Haha, I know this. Doesn't matter, thanks for your help !

I'm gonna add a "thanks" section to mention people who helped this tutorial.

**Comment by GuillaumeGomez** [comment]
I added a contributors section at the summary of the tutorial. It's generated from the contributors list on github. So you're in it. :)

**Comment by k0pernicus** [comment]
Woo! Thanks a lot :-)

**Pull request merged**
